name: CI

on:
  push:
    branches:
      - fcitx
  pull_request:
    branches:
      - fcitx

jobs:
  check:
    name: Build and test
    runs-on: ubuntu-latest
    container: archlinux:latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        include:
          - compiler: gcc
            cxx_compiler: g++
          - compiler: clang
            cxx_compiler: clang++
    env:
      CC: ${{ matrix.compiler }}
      CXX: ${{ matrix.cxx_compiler }}
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm base-devel clang cmake ninja extra-cmake-modules fmt libuv boost git qt6-base qt6-wayland libxkbcommon qt6-webengine bazel
      - uses: actions/checkout@v4
        with:
          repository: fcitx/fcitx5
          path: fcitx5
      - name: Cache fcitx5 data files
        uses: actions/cache@v4
        with:
          path: 'fcitx5/**/*.tar.*'
          key: ${{ runner.os }}-${{ hashFiles('fcitx5/src/modules/spell/CMakeLists.txt') }}
      - name: Build and Install fcitx5
        uses: fcitx/github-actions@cmake
        with:
          path: fcitx5
          cmake-option: >-
            -DENABLE_KEYBOARD=Off
            -DENABLE_X11=Off
            -DENABLE_WAYLAND=Off
            -DENABLE_ENCHANT=Off
            -DENABLE_DBUS=Off
            -DENABLE_SERVER=Off
            -DENABLE_EMOJI=Off
            -DUSE_SYSTEMD=Off
      - uses: actions/checkout@v4
        with:
          path: mozc
          submodules: true
      - name: Init CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: cpp
          source-root: mozc/src/unix/fcitx5
      - name: Build fcitx5-mozc
        shell: bash
        run: |
          cd mozc/src/
          PKG_CONFIG_PATH=/opt/fcitx/lib/pkgconfig _BUILD_TARGETS=unix/fcitx5:fcitx5-mozc.so ../scripts/build_fcitx5_bazel --cxxopt=-Wno-uninitialized --host_cxxopt=-Wno-uninitialized --linkopt=-L/opt/fcitx/lib
      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v2
